apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: baktrack-alerts
  namespace: monitoring
  labels:
    release: kps
spec:
  groups:
    - name: baktrack.rules
      rules:
        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod {{ $labels.pod }} is crash-looping"
