apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yash-Rathod/helm-charts.git
    targetRevision: main
    path: charts/notification-api
    helm:
      values: |
        image:
          repository: 347486023960.dkr.ecr.ap-south-1.amazonaws.com/notification-api
          tag: d44a01e
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
